### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by shi-yan** [soramitsu/libp2p#35]
it tries to upload something to the cache repo

```
Error:
  Repository not found 'https://github.com/soramitsu/hunter-binary-cache' or user 'shi-yan' has no access to it
Traceback (most recent call last):
  File "/root/.hunter/_Base/Download/Hunter/0.23.216/a492a18/Unpacked/scripts/upload-cache-to-github.py", line 594, in <module>
    cache.upload_raw(github)
  File "/root/.hunter/_Base/Download/Hunter/0.23.216/a492a18/Unpacked/scripts/upload-cache-to-github.py", line 292, in upload_raw
    i.upload_raw(github)
  File "/root/.hunter/_Base/Download/Hunter/0.23.216/a492a18/Unpacked/scripts/upload-cache-to-github.py", line 256, in upload_raw
    github.upload_raw_file(raw)
  File "/root/.hunter/_Base/Download/Hunter/0.23.216/a492a18/Unpacked/scripts/upload-cache-to-github.py", line 227, in upload_raw_file
    release_id, upload_url = self.get_release_by_tag(tagname)
  File "/root/.hunter/_Base/Download/Hunter/0.23.216/a492a18/Unpacked/scripts/upload-cache-to-github.py", line 55, in func_out
    raise err
  File "/root/.hunter/_Base/Download/Hunter/0.23.216/a492a18/Unpacked/scripts/upload-cache-to-github.py", line 49, in func_out
    return func_in(*args, **kwargs)
  File "/root/.hunter/_Base/Download/Hunter/0.23.216/a492a18/Unpacked/scripts/upload-cache-to-github.py", line 118, in get_release_by_tag
    format(repo_name, self.username)
__main__.Error: Repository not found 'https://github.com/soramitsu/hunter-binary-cache' or user 'shi-yan' has no access to it

[hunter ** INTERNAL **] Upload script failed
```

I don't have write access to https://github.com/soramitsu/hunter-binary-cache

**Comment by igor-egorov** [comment]
Hi @shi-yan,

Unfortunately, CMake of this project has a hard-coded Hunter Binary Cache repository address, which now can be used only by Soramitsu workers.

Sorry for that inconvenience! Please try without specifying GITHUB_HUNTER_TOKEN and GITHUB_HUNTER_USERNAME variables - it should work.

**Comment by shi-yan** [comment]
Thank you. I confirm without the envvar I could build it
